rabbitmq:
  connectionURL: amqp://guest:guest@localhost:5672/
  publishQueues:
    - exchange: summary-exchange
      bindingQueue:
        - queue: summaryQ
          routingKey: summary.*
server:
  port: 8090
