rabbitmq:
  connectionURL: amqp://guest:guest@localhost:5672/
  publishQueues:
    - exchange: summary-exchange
      bindingQueue:
        - queue: summaryQ
          routingKey: summary.*
server:
  port: 7103

spring:
  data:
    mongodb:
      host: mongodb_summary
      port: 7203
      database: summary-db
